name: Prison
version: '${project.version}'
main: me.topilov.App
api-version: 1.13
commands:
  menu: {}
  mines: {}
  mine: {}
  shop: {}
  eco: {}
  sell: {}
  prison: {}
  add_mine: {}
  test: {}
  thanks: {}